### ISSUE TITLE
Add Posting Ability To Back End

### ISSUE THREAD

**Issue by Superior126** [Superior126/easy-newsroom-server#3]
Add the ability for the back end to accept new posts.

**Tasks**

- [ ] Create new post route
- [ ] Create a form so the client can add data to it
- [ ] Create a system for storing posts in a database
- [ ] Create a system for handling content uploaded by site owners
